### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by hoodsy** [AJFunk/cannabis-reports#1]
The package doesn't seem to be installing properly. I tried node versions 4.6.1 and 7.2.1. I'm getting this error when trying to install from NPM:

```
Error: Cannot find module 'cannabis-reports'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

Can't wait to start playing with this API though!

**Comment by AJFunk** [comment]
Is this error being thrown when you try to run your app? Not when you're trying to `npm i cannabis-reports` right?

I'm not seeing any issues with the installation, can you include a code snippet? Perhaps your import path is incorrect?

If it is being thrown while trying to install, what NPM version are you using?

**Comment by hoodsy** [comment]
The error is in my app, and it's after installation. I think it has to do with the setup from NPM - right now I'm just importing a cloned copy of the repo.

That error is when trying to import ```cannabis-reports``` like other npm packages: 
```import { Strain } from 'cannabis-reports'```

**Comment by AJFunk** [comment]
Is it working with the cloned version?

After installing, is the `cannabis-reports` directory in your `node_modules`?

**Comment by hoodsy** [comment]
Yeah it works when I require from the src directory. cannabis-reports is in
my node_modules.

**Comment by AJFunk** [comment]
Have you tried removing it from your node_modules and reinstalling? If you have it a link to the repo for your project, I can take a look 😃

**Comment by hoodsy** [comment]
I have, it's alright though I have my workaround. thanks for the quick response 👍

**Comment by gotwalt** [comment]
Experienced the same thing - after doing some digging, realized that nothing aside from the `package.json`, license, and readme are actually getting installed via NPM. You can see this in action [via runkit](https://runkit.com/58a4f5e22448b700144a26c3/58a4f5e22448b700144a26c4). This is likely because the `package.json` doesn't [list any files](https://docs.npmjs.com/files/package.json#files) to be distributed.

**Comment by AJFunk** [comment]
Thanks for finding that. I had `lib` in the .gitignore, so it wasn't being included. Should be working now, try reinstalling.

**Comment by gotwalt** [comment]
* You'll still need to add the files to be distributed via NPM to the files section of package.json explicitly. Unless the file / directory is listed, it won't get built into the package.

* You'll also have to bump your version, rebuild, and upload the new package to NPM for these changes to take effect.

**Comment by gotwalt** [comment]
Scratch that - it's all there now. Thanks!
