### ISSUE TITLE
API Keys?

### ISSUE THREAD

**Issue by rtiwariops** [AJFunk/cannabis-reports#5]
Where can i get the api keys from?

**Comment by arronhunt** [comment]
I've tried multiple times to get API keys from the creators, including personal emails and reaching out to them on social networks. 

There's a request form on cannabisreports.com but I haven't had success with it.

**Comment by AJFunk** [comment]
It took me a while to get keys from them also, and that was a few years ago. It doesn't look like they've had social media activity in over a year, so I suspect their project may be dead unfortunately :(

**Comment by rtiwariops** [comment]
Thanks for the reply. Can you get the license information of seller and
grower using these api?

**Comment by AJFunk** [comment]
I'm not sure, their API documentation is no longer active which just reinforces that their API probably doesn't work anymore
